"""Initial migration with tools_ prefix

Revision ID: 4892bf59ba61
Revises: 
Create Date: 2025-11-27 12:36:00.623881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4892bf59ba61'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tools_directory_groups',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('directory_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('idp_id', sa.String(length=255), nullable=True),
    sa.Column('mapped_role', sa.String(length=50), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_directory_groups_directory', 'tools_directory_groups', ['directory_id'], unique=False)
    op.create_index('idx_directory_groups_name', 'tools_directory_groups', ['name'], unique=False)
    op.create_table('tools_system_config',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('config_key', sa.String(length=100), nullable=False),
    sa.Column('config_value', sa.Text(), nullable=False),
    sa.Column('is_secret', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('config_key')
    )
    op.create_table('tools_tool_presets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('preset_name', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('tools', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('preset_name')
    )
    op.create_table('tools_tool_registry',
    sa.Column('tool_name', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('auth_type', sa.String(length=20), nullable=False),
    sa.Column('config_schema', sa.JSON(), nullable=False),
    sa.Column('required_oauth', sa.JSON(), nullable=True),
    sa.Column('icon_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('tool_name')
    )
    op.create_table('tools_users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('workspace_id', sa.String(length=36), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_super_admin', sa.Boolean(), nullable=False),
    sa.Column('directory_sync_id', sa.String(length=100), nullable=True),
    sa.Column('idp_id', sa.String(length=255), nullable=True),
    sa.Column('provisioned_via', sa.String(length=50), nullable=False),
    sa.Column('mfa_enabled', sa.Boolean(), nullable=False),
    sa.Column('mfa_grace_period_end', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['tools_workspaces.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('idx_users_directory_sync', 'tools_users', ['directory_sync_id'], unique=False)
    op.create_index('idx_users_idp', 'tools_users', ['idp_id'], unique=False)
    op.create_index('idx_users_workspace', 'tools_users', ['workspace_id'], unique=False)
    op.create_table('tools_workspaces',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=True),
    sa.Column('workos_org_id', sa.String(length=100), nullable=True),
    sa.Column('settings', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['tools_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug'),
    sa.UniqueConstraint('workos_org_id')
    )
    op.create_index('idx_workspaces_owner', 'tools_workspaces', ['owner_id'], unique=False)
    op.create_index('idx_workspaces_workos_org', 'tools_workspaces', ['workos_org_id'], unique=False)
    op.create_table('tools_audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=True),
    sa.Column('actor_email', sa.String(length=255), nullable=True),
    sa.Column('actor_type', sa.String(length=50), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=True),
    sa.Column('target_id', sa.String(length=255), nullable=True),
    sa.Column('target_name', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('request_id', sa.String(length=36), nullable=True),
    sa.Column('event_metadata', sa.JSON(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['tools_workspaces.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_action', 'tools_audit_logs', ['action'], unique=False)
    op.create_index('idx_audit_actor', 'tools_audit_logs', ['actor_id'], unique=False)
    op.create_index('idx_audit_category', 'tools_audit_logs', ['category'], unique=False)
    op.create_index('idx_audit_occurred', 'tools_audit_logs', ['occurred_at'], unique=False)
    op.create_index('idx_audit_request', 'tools_audit_logs', ['request_id'], unique=False)
    op.create_index('idx_audit_target', 'tools_audit_logs', ['target_type', 'target_id'], unique=False)
    op.create_index('idx_audit_workspace', 'tools_audit_logs', ['workspace_id'], unique=False)
    op.create_table('tools_directory_sync_users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('directory_id', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('idp_id', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=False),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['tools_users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_dsync_users_directory', 'tools_directory_sync_users', ['directory_id'], unique=False)
    op.create_index('idx_dsync_users_email', 'tools_directory_sync_users', ['email'], unique=False)
    op.create_index('idx_dsync_users_idp', 'tools_directory_sync_users', ['idp_id'], unique=False)
    op.create_index('idx_dsync_users_state', 'tools_directory_sync_users', ['state'], unique=False)
    op.create_table('tools_oauth_tokens',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('tool_name', sa.String(length=100), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('scopes', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['tools_users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['tools_workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_oauth_tokens_lookup', 'tools_oauth_tokens', ['user_id', 'tool_name'], unique=False)
    op.create_index('idx_oauth_tokens_unique', 'tools_oauth_tokens', ['workspace_id', 'tool_name', 'provider'], unique=True)
    op.create_index('idx_oauth_tokens_workspace', 'tools_oauth_tokens', ['workspace_id', 'tool_name'], unique=False)
    op.create_table('tools_tool_configs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('tool_name', sa.String(length=100), nullable=False),
    sa.Column('config_key', sa.String(length=100), nullable=False),
    sa.Column('config_value', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['tools_users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['tools_workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_tool_configs_lookup', 'tools_tool_configs', ['user_id', 'tool_name'], unique=False)
    op.create_index('idx_tool_configs_unique', 'tools_tool_configs', ['workspace_id', 'tool_name', 'config_key'], unique=True)
    op.create_index('idx_tool_configs_workspace', 'tools_tool_configs', ['workspace_id', 'tool_name'], unique=False)
    op.create_table('tools_user_base_folders',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_scanned_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['tools_users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['tools_workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_base_folders_active', 'tools_user_base_folders', ['is_active'], unique=False)
    op.create_index('idx_base_folders_user', 'tools_user_base_folders', ['user_id'], unique=False)
    op.create_index('idx_base_folders_workspace', 'tools_user_base_folders', ['workspace_id'], unique=False)
    op.create_table('tools_user_tools',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('tool_name', sa.String(length=100), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['tools_users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['tools_workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_tools_lookup', 'tools_user_tools', ['user_id', 'enabled'], unique=False)
    op.create_index('idx_user_tools_unique', 'tools_user_tools', ['workspace_id', 'tool_name'], unique=True)
    op.create_index('idx_user_tools_workspace', 'tools_user_tools', ['workspace_id', 'tool_name'], unique=False)
    op.create_table('tools_directory_group_memberships',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('group_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['tools_directory_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['tools_directory_sync_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_dgm_group', 'tools_directory_group_memberships', ['group_id'], unique=False)
    op.create_index('idx_dgm_unique', 'tools_directory_group_memberships', ['group_id', 'user_id'], unique=True)
    op.create_index('idx_dgm_user', 'tools_directory_group_memberships', ['user_id'], unique=False)
    op.create_table('tools_projects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('base_folder_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('git_remote_url', sa.Text(), nullable=True),
    sa.Column('has_genie_folder', sa.Boolean(), nullable=False),
    sa.Column('agent_count', sa.String(length=10), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('discovered_at', sa.DateTime(), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['base_folder_id'], ['tools_user_base_folders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['tools_workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_projects_active', 'tools_projects', ['is_active'], unique=False)
    op.create_index('idx_projects_base_folder', 'tools_projects', ['base_folder_id'], unique=False)
    op.create_index('idx_projects_has_genie', 'tools_projects', ['has_genie_folder'], unique=False)
    op.create_index('idx_projects_workspace', 'tools_projects', ['workspace_id'], unique=False)
    op.create_table('tools_agents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('relative_path', sa.Text(), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('executor', sa.String(length=50), nullable=True),
    sa.Column('variant', sa.String(length=50), nullable=True),
    sa.Column('model', sa.String(length=50), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=False),
    sa.Column('toolkit', sa.JSON(), nullable=True),
    sa.Column('raw_frontmatter', sa.JSON(), nullable=True),
    sa.Column('sync_status', sa.String(length=20), nullable=False),
    sa.Column('synced_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['tools_projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['tools_workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_agents_file_path', 'tools_agents', ['file_path'], unique=True)
    op.create_index('idx_agents_project', 'tools_agents', ['project_id'], unique=False)
    op.create_index('idx_agents_sync_status', 'tools_agents', ['sync_status'], unique=False)
    op.create_index('idx_agents_workspace', 'tools_agents', ['workspace_id'], unique=False)
    op.create_table('tools_project_tools',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('tool_name', sa.String(length=100), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['tools_projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['tools_workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_project_tools_project', 'tools_project_tools', ['project_id'], unique=False)
    op.create_index('idx_project_tools_unique', 'tools_project_tools', ['project_id', 'tool_name'], unique=True)
    op.create_index('idx_project_tools_workspace', 'tools_project_tools', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_project_tools_workspace', table_name='tools_project_tools')
    op.drop_index('idx_project_tools_unique', table_name='tools_project_tools')
    op.drop_index('idx_project_tools_project', table_name='tools_project_tools')
    op.drop_table('tools_project_tools')
    op.drop_index('idx_agents_workspace', table_name='tools_agents')
    op.drop_index('idx_agents_sync_status', table_name='tools_agents')
    op.drop_index('idx_agents_project', table_name='tools_agents')
    op.drop_index('idx_agents_file_path', table_name='tools_agents')
    op.drop_table('tools_agents')
    op.drop_index('idx_projects_workspace', table_name='tools_projects')
    op.drop_index('idx_projects_has_genie', table_name='tools_projects')
    op.drop_index('idx_projects_base_folder', table_name='tools_projects')
    op.drop_index('idx_projects_active', table_name='tools_projects')
    op.drop_table('tools_projects')
    op.drop_index('idx_dgm_user', table_name='tools_directory_group_memberships')
    op.drop_index('idx_dgm_unique', table_name='tools_directory_group_memberships')
    op.drop_index('idx_dgm_group', table_name='tools_directory_group_memberships')
    op.drop_table('tools_directory_group_memberships')
    op.drop_index('idx_user_tools_workspace', table_name='tools_user_tools')
    op.drop_index('idx_user_tools_unique', table_name='tools_user_tools')
    op.drop_index('idx_user_tools_lookup', table_name='tools_user_tools')
    op.drop_table('tools_user_tools')
    op.drop_index('idx_base_folders_workspace', table_name='tools_user_base_folders')
    op.drop_index('idx_base_folders_user', table_name='tools_user_base_folders')
    op.drop_index('idx_base_folders_active', table_name='tools_user_base_folders')
    op.drop_table('tools_user_base_folders')
    op.drop_index('idx_tool_configs_workspace', table_name='tools_tool_configs')
    op.drop_index('idx_tool_configs_unique', table_name='tools_tool_configs')
    op.drop_index('idx_tool_configs_lookup', table_name='tools_tool_configs')
    op.drop_table('tools_tool_configs')
    op.drop_index('idx_oauth_tokens_workspace', table_name='tools_oauth_tokens')
    op.drop_index('idx_oauth_tokens_unique', table_name='tools_oauth_tokens')
    op.drop_index('idx_oauth_tokens_lookup', table_name='tools_oauth_tokens')
    op.drop_table('tools_oauth_tokens')
    op.drop_index('idx_dsync_users_state', table_name='tools_directory_sync_users')
    op.drop_index('idx_dsync_users_idp', table_name='tools_directory_sync_users')
    op.drop_index('idx_dsync_users_email', table_name='tools_directory_sync_users')
    op.drop_index('idx_dsync_users_directory', table_name='tools_directory_sync_users')
    op.drop_table('tools_directory_sync_users')
    op.drop_index('idx_audit_workspace', table_name='tools_audit_logs')
    op.drop_index('idx_audit_target', table_name='tools_audit_logs')
    op.drop_index('idx_audit_request', table_name='tools_audit_logs')
    op.drop_index('idx_audit_occurred', table_name='tools_audit_logs')
    op.drop_index('idx_audit_category', table_name='tools_audit_logs')
    op.drop_index('idx_audit_actor', table_name='tools_audit_logs')
    op.drop_index('idx_audit_action', table_name='tools_audit_logs')
    op.drop_table('tools_audit_logs')
    op.drop_index('idx_workspaces_workos_org', table_name='tools_workspaces')
    op.drop_index('idx_workspaces_owner', table_name='tools_workspaces')
    op.drop_table('tools_workspaces')
    op.drop_index('idx_users_workspace', table_name='tools_users')
    op.drop_index('idx_users_idp', table_name='tools_users')
    op.drop_index('idx_users_directory_sync', table_name='tools_users')
    op.drop_table('tools_users')
    op.drop_table('tools_tool_registry')
    op.drop_table('tools_tool_presets')
    op.drop_table('tools_system_config')
    op.drop_index('idx_directory_groups_name', table_name='tools_directory_groups')
    op.drop_index('idx_directory_groups_directory', table_name='tools_directory_groups')
    op.drop_table('tools_directory_groups')
    # ### end Alembic commands ###
