"""Initial migration

Revision ID: 2a788fa36f8a
Revises: 
Create Date: 2025-11-23 17:21:14.094571

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a788fa36f8a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tool_presets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('preset_name', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('tools', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('preset_name')
    )
    op.create_table('tool_registry',
    sa.Column('tool_name', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('auth_type', sa.String(length=20), nullable=False),
    sa.Column('config_schema', sa.JSON(), nullable=False),
    sa.Column('required_oauth', sa.JSON(), nullable=True),
    sa.Column('icon_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('tool_name')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('oauth_tokens',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('tool_name', sa.String(length=100), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('scopes', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_oauth_tokens_lookup', 'oauth_tokens', ['user_id', 'tool_name'], unique=False)
    op.create_index('idx_oauth_tokens_unique', 'oauth_tokens', ['user_id', 'tool_name', 'provider'], unique=True)
    op.create_table('tool_configs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('tool_name', sa.String(length=100), nullable=False),
    sa.Column('config_key', sa.String(length=100), nullable=False),
    sa.Column('config_value', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_tool_configs_lookup', 'tool_configs', ['user_id', 'tool_name'], unique=False)
    op.create_index('idx_tool_configs_unique', 'tool_configs', ['user_id', 'tool_name', 'config_key'], unique=True)
    op.create_table('user_tools',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('tool_name', sa.String(length=100), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_tools_lookup', 'user_tools', ['user_id', 'enabled'], unique=False)
    op.create_index('idx_user_tools_unique', 'user_tools', ['user_id', 'tool_name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_user_tools_unique', table_name='user_tools')
    op.drop_index('idx_user_tools_lookup', table_name='user_tools')
    op.drop_table('user_tools')
    op.drop_index('idx_tool_configs_unique', table_name='tool_configs')
    op.drop_index('idx_tool_configs_lookup', table_name='tool_configs')
    op.drop_table('tool_configs')
    op.drop_index('idx_oauth_tokens_unique', table_name='oauth_tokens')
    op.drop_index('idx_oauth_tokens_lookup', table_name='oauth_tokens')
    op.drop_table('oauth_tokens')
    op.drop_table('users')
    op.drop_table('tool_registry')
    op.drop_table('tool_presets')
    # ### end Alembic commands ###
