# Google Cloud Run service configuration example
# Deploy with: gcloud run services replace gcloud-cloudrun.yaml

apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: automagik-mcp-sse
  labels:
    cloud.googleapis.com/location: us-central1
  annotations:
    run.googleapis.com/launch-stage: GA
spec:
  template:
    metadata:
      annotations:
        # Maximum number of requests per container instance
        run.googleapis.com/execution-environment: gen2
        autoscaling.knative.dev/maxScale: "100"
        autoscaling.knative.dev/minScale: "0"
    spec:
      containerConcurrency: 100
      timeoutSeconds: 300
      serviceAccountName: automagik-sa@PROJECT_ID.iam.gserviceaccount.com
      containers:
      - name: automagik-mcp
        image: gcr.io/PROJECT_ID/automagik-mcp:latest
        ports:
        - name: http1
          containerPort: 8000  # 8080 for HTTP transport
        env:
        - name: TRANSPORT
          value: "sse"  # or "http"
        - name: HOST
          value: "0.0.0.0"
        - name: PORT
          value: "8000"  # 8080 for HTTP transport
        # Secrets from Secret Manager
        - name: EVOLUTION_API_KEY
          valueFrom:
            secretKeyRef:
              name: evolution-api-key
              key: latest
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: openai-api-key
              key: latest
        resources:
          limits:
            cpu: "2"
            memory: "2Gi"
          requests:
            cpu: "1"
            memory: "512Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 0
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
  traffic:
  - percent: 100
    latestRevision: true